#!/usr/bin/env python3
"""Copy free-exercise-db WebP demos onto warm-up / cool-down mobility ids
ONLY when the source is a true visual match.

Stick demos (cat-cow, cobra, bird-dog, etc.) are produced by
generate-mobility-stick-demos.py — do not overwrite those with wrong FEDB copies.

Keep SOURCE_MAP in sync with MobilityCatalog.cs SourceDemoId (non-null values only).
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEMOS = ROOT / "WorkoutPlanner.Api" / "wwwroot" / "demos"

# mobility id → source exercise id (must already have a .webp from build-exercise-webps.py)
# Only include true visual matches — others use stick demos.
SOURCE_MAP = {
    "wu-march": "step-up-with-knee-raise",
    "wu-jacks": "star-jump",
    "wu-high-knees": "knee-tuck-jump",
    "wu-band-disloc": "band-pull-apart",
    "wu-dead-bug": "dead-bug",
    "wu-bw-squat": "bodyweight-squat",
    "wu-glute-bridge": "butt-lift-bridge",
    "wu-calf-raise": "standing-calf-raises",
    "cd-ham-hinge": "stiff-leg-barbell-good-morning",
}

# Generated by generate-mobility-stick-demos.py — never overwrite with FEDB copies
STICK_ONLY = {
    "wu-arm-circles",
    "wu-scap-pushup",
    "wu-cat-cow",
    "wu-bird-dog",
    "wu-hip-circles",
    "wu-leg-swings",
    "wu-wrist-circles",
    "wu-shoulder-rolls",
    "wu-torso-twist",
    "cd-chest-door",
    "cd-tricep-oh",
    "cd-cross-body",
    "cd-child-pose",
    "cd-thread-needle",
    "cd-quad-stand",
    "cd-fig4",
    "cd-calf-wall",
    "cd-hip-flexor",
    "cd-cobra",
    "cd-knees-chest",
    "cd-forearm-stretch",
    "cd-neck-side",
    "cd-breathe",
}


def refresh_index():
    import json

    ids = sorted(p.stem for p in DEMOS.glob("*.webp") if not p.name.startswith("_"))
    (DEMOS / "index.json").write_text(
        json.dumps(
            {
                "format": "webp",
                "pathPattern": "/demos/{id}.webp",
                "count": len(ids),
                "ids": ids,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"updated index.json ({len(ids)} demos)")


def main():
    DEMOS.mkdir(parents=True, exist_ok=True)
    ok = miss = skip = 0
    for mob_id, src_id in SOURCE_MAP.items():
        if mob_id in STICK_ONLY:
            print(f"  SKIP stick-only {mob_id}")
            skip += 1
            continue
        src = DEMOS / f"{src_id}.webp"
        dst = DEMOS / f"{mob_id}.webp"
        if not src.exists():
            print(f"  MISS source {src_id} for {mob_id}")
            miss += 1
            continue
        shutil.copy2(src, dst)
        print(f"  {mob_id} ← {src_id} ({dst.stat().st_size // 1024} KB)")
        ok += 1
    print(f"Done: {ok} copied, {miss} missing, {skip} stick-only left alone")
    refresh_index()


if __name__ == "__main__":
    main()
